name: Build EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyinstaller pyautogui

      - name: Build EXE
        run: |
          pyinstaller --onefile --console robot_emulator.py

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: robot_emulator
          path: dist/robot_emulator.exe
